---
image:
  repository: 'dor-sat06ip-01.p.uintra.net:5000/ansc/openstack-project-manager'
  tag: v0.1.0
  pullPolicy: Always 

# Set the schedule for every run, it's in crontab format, defaults to every sunday at 1am if not set  
schedule: "0 * * * *"

# Set the cloud config from clouds.yml to be used
cloud: "admin"

# Generate a secret for clouds.yml
clouds_yml_config: |
  clouds.yml: |
      clouds:
        default:
          region_name: your-region-here
          auth:
            username: your-user-here
            password: your-password-here
            project_name: your-project-here
            project_domain_name: 'Default'
            user_domain_name: 'Default'
            auth_url: 'http://your-url-here:5000/v3'
