{{- range $jobname, $job := .Values.jobs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ (first $job.volumes).secret.secretName }}
  labels:
    {{- include "cronjobs.labels" $ | nindent 4 }}
type: Opaque
{{- end }}
{{- range $name, $secret := .Values.secrets }}
data:
  {{- range $name, $value := $secret.data }}
  {{ $name }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- range $name, $path := $secret.files }}
  {{ $name }}: {{ $.Files.Get $path | b64enc | quote }}
  {{- end }}
{{- end }}
