{{- range $jobname, $job := .Values.jobs }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ (first $job.volumes).secret.secretName }}
  labels:
    {{- include "cronjobs.labels" $ | nindent 4 }}
type: Opaque
stringData:
  clouds.yml: |
{{ toYaml  $job.clouds_yml_config | indent 4 }}
{{- end }}
