## OSISM Openstack Image Manager
##
##
image:
  # Use gitlab.com as registry
  registry: registry.gitlab.com
  image: andischrogl/registry/openstack-image-manager
  tag: v0.20240710.0
  pullPolicy: Always 

# Set the schedule for every run, it's in crontab format, defaults to every sunday at 1am if not set  
schedule: "0 1 * * 7"

# Set the Filter for Image Names you want to update, leave empty for all images to be updates in repository
# example: "CentOS|Debian|Ubuntu"
filter: ""

# Set the cloud config from clouds.yml to be used
cloud: "default"

# Generate a secret for clouds.yml
clouds_yml_config: |
  clouds.yml: |
      clouds:
        default:
          region_name: your-region-here
          auth:
            username: your-user-here
            password: your-password-here
            project_name: your-project-here
            project_domain_name: 'Default'
            user_domain_name: 'Default'
            auth_url: 'http://your-url-here:5000/v3'
