# Default Values
jobs:
  openstack-image-manager:
    securityContext:
      runAsUser: 8000
      runAsGroup: 8000
    image:
      # Use gitlab.com as registry
      registry: registry.gitlab.com
      image: andischrogl/registry/openstack-image-manager
      tag: v0.20240812.0
      imagePullPolicy: Always 
    env:
      - name: CLOUD
        #  Set the cloud config from clouds.yml to be used 
        value: "openstack"
      - name: FILTER
        # Set the Filter for Image Names you want to update, leave empty for all images to be updates in repository 
        # like "CentOS|Cirros|Ubuntu|Debian|openSUSE|Rocky"
        value: ""
    # Set the Cron schedule
    schedule: "0 1 * * 7"
    serviceAccount:
      name: "openstack-image-manager"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumeMounts:
      - mountPath: "/etc/openstack/clouds.yml"
        subPath: clouds.yml
        name: oim-clouds-credentials 
        readOnly: true
    volumes:
      - name: oim-clouds-credentials
        secret:
          secretName: oim-openstack-image-manager 
          items:
            - key: clouds.yml
              path: clouds.yml

secrets:
  clouds-credentials:
    files:
      # Set the path to your clouds.yaml file for import
      # e.g. "/home/user/clouds.yaml"
      clouds.yml: clouds.yml

