# Default Values
jobs:
  openstack-image-manager:
    securityContext:
      runAsUser: 8000
      runAsGroup: 8000
    image:
      # Use gitlab.com as registry
      registry: registry.gitlab.com
      image: andischrogl/registry/openstack-image-manager
      tag: v0.20240710.0
      imagePullPolicy: Always 
    env:
      - name: CLOUD
        #  Set the cloud config from clouds.yml to be used 
        value: "default"
      - name: FILTER
        # Set the Filter for Image Names you want to update, leave empty for all images to be updates in repository 
        # like "CentOS|Cirros|Ubuntu|Debian|openSUSE|Rocky"
        value: ""
    # Set your Timezone
    timezone: "Europe/Berlin"
    # Set the Cron schedule
    schedule: "0 1 * * 6"
    serviceAccount:
      name: "openstack-image-manager"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 3
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    volumeMounts:
      - mountPath: "/etc/openstack/clouds.yml"
        subPath: clouds.yml
        name: oim-clouds-credentials 
        readOnly: true
    volumes:
      - name: oim-clouds-credentials
        secret:
          secretName: oim-openstack-image-manager 
          items:
            - key: clouds.yml
              path: clouds.yml
    clouds_yml_config: 
          clouds:
            default:
              region_name: your-region-here
              auth:
                username: your-user-here
                password: your-password-here
                project_name: your-project-here
                project_domain_name: 'Default'
                user_domain_name: 'Default'

